# **Basic Python**

### **1. Split this string**

In [8]:
s="Hi there Maddy!"
s.split()

['Hi', 'there', 'Maddy!']

### **2. Use .format() to print the following string.**

Output should be: The diameter of Earth is 12742 kilometers.bold text

In [9]:
planet="Earth"
diameter=12742

In [10]:
print("The diameter of {} is {} kilometer".format(planet,diameter));

The diameter of Earth is 12742 kilometer


### **3. In this nest dictionary grab the word "hello"**


In [11]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [12]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

## **Numpy**

In [13]:
import numpy as np

**4.1 Create an array of 10 zeros?**

**4.2 Create an array of 10 threes?**

In [14]:
a=np.zeros(10)

In [15]:
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
b=np.ones(10)*3
b

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

### **5. Create an array of all the even integers from 30 to 55**

In [17]:
s=np.arange(30,55,2)

In [18]:
s

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54])

### **6. Create a 5x5 matrix with values ranging from 0 to 25**

In [19]:
b=np.arange(0,25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### **7. Concatinate a and b**
**a = [3, 5, 7]**

**b = [2, 4, 6]**

In [20]:
a=np.array([3,5,7])
b=np.array([2,4,6])

In [21]:
np.concatenate((a,b))

array([3, 5, 7, 2, 4, 6])

### **7.1 . Concatinate a and b with sort**


In [22]:
k=sorted(np.concatenate((a,b),axis=0))
k

[2, 3, 4, 5, 6, 7]

## **Pandas**

In [28]:
import pandas as pd

In [29]:
d = {"names":["Raampradaap","jeevanantham","saravanakumar","jeevanantham","Sasireka"],"age":[20,20,20,20,20]}
df = pd.DataFrame(d)
df

names  age
0    Raampradaap   20
1   jeevanantham   20
2  saravanakumar   20
3   jeevanantham   20
4       Sasireka   20

### **9. Generate the series of dates from 1st Nov, 2022 to 31th Dec, 2022**

In [25]:
m= pd.date_range(start='1-11-2022',end='31-12-2022')
for i in m:
  print(i)

2022-01-11 00:00:00
2022-01-12 00:00:00
2022-01-13 00:00:00
2022-01-14 00:00:00
2022-01-15 00:00:00
2022-01-16 00:00:00
2022-01-17 00:00:00
2022-01-18 00:00:00
2022-01-19 00:00:00
2022-01-20 00:00:00
2022-01-21 00:00:00
2022-01-22 00:00:00
2022-01-23 00:00:00
2022-01-24 00:00:00
2022-01-25 00:00:00
2022-01-26 00:00:00
2022-01-27 00:00:00
2022-01-28 00:00:00
2022-01-29 00:00:00
2022-01-30 00:00:00
2022-01-31 00:00:00
2022-02-01 00:00:00
2022-02-02 00:00:00
2022-02-03 00:00:00
2022-02-04 00:00:00
2022-02-05 00:00:00
2022-02-06 00:00:00
2022-02-07 00:00:00
2022-02-08 00:00:00
2022-02-09 00:00:00
2022-02-10 00:00:00
2022-02-11 00:00:00
2022-02-12 00:00:00
2022-02-13 00:00:00
2022-02-14 00:00:00
2022-02-15 00:00:00
2022-02-16 00:00:00
2022-02-17 00:00:00
2022-02-18 00:00:00
2022-02-19 00:00:00
2022-02-20 00:00:00
2022-02-21 00:00:00
2022-02-22 00:00:00
2022-02-23 00:00:00
2022-02-24 00:00:00
2022-02-25 00:00:00
2022-02-26 00:00:00
2022-02-27 00:00:00
2022-02-28 00:00:00
2022-03-01 00:00:00


E:\IBM\lib\site-packages\IPython\core\interactiveshell.py:3457: UserWarning: Parsing '31-12-2022' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  exec(code_obj, self.user_global_ns, self.user_ns)


### **10. Create 2D list to DataFrame**

**l = [[1, 'Jeevanantham', 20], [2, 'saravanakumar', 20], [3, 'Sasireka', 20],[4,'Raampradaap',20],[5,'Jeevanantham',20]]
]**

In [26]:
l= [[1, 'Jeevanantham', 20], [2, 'saravanakumar', 20], [3, 'Sasireka', 20],[4,'Raampradaap',20],[5,'Jeevanantham',20]]


In [27]:
print(pd.DataFrame(l))

   0              1   2
0  1   Jeevanantham  20
1  2  saravanakumar  20
2  3       Sasireka  20
3  4    Raampradaap  20
4  5   Jeevanantham  20
